export const REDIS_CACHE = {
  HOST: 'REDIS_CACHE_HOST',
  PORT: 'REDIS_CACHE_PORT',
  PASSWORD: 'REDIS_CACHE_PASSWORD',
  DB: 'REDIS_CACHE_DB',
} as const;

export const REDIS_PUB_SUB = {
  HOST: 'REDIS_PUB_SUB_HOST',
  PORT: 'REDIS_PUB_SUB_PORT',
  PASSWORD: 'REDIS_PUB_SUB_PASSWORD',
  DB: 'REDIS_PUB_SUB_DB',
} as const;
